## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Norell Party"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Alex and Mariah Norell invite you to a party celebration thingy on September 10, 2022."
  logo = "images/san_jose.jpg"
  favicon = true
